### ISSUE TITLE
[clearml-agent] queue creation failed

### ISSUE THREAD

**Issue by cedricve** [allegroai/clearml-helm-charts#317] opened 2024-08-20 12:22 UTC
### Describe the bug a clear and concise description of what the bug is.

I'm assigning an agent to a non-existing queue, and turned on the createQueueIfNotExists variable. I get following error from the pod, while trying to create the queue on our behalf.

    + python3 k8s_glue_example.py --queue nvidia-scheduler --namespace clearml --template-yaml /root/template/template.yaml --create-queue
    /usr/local/lib/python3.6/dist-packages/jwt/utils.py:7: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
      from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
    usage: k8s_glue_example.py [-h] [--queue QUEUE] [--ports-mode]
                               [--num-of-services NUM_OF_SERVICES]
                               [--base-port BASE_PORT]
                               [--base-pod-num BASE_POD_NUM]
                               [--gateway-address GATEWAY_ADDRESS]
                               [--pod-clearml-conf POD_CLEARML_CONF]
                               [--overrides-yaml OVERRIDES_YAML]
                               [--template-yaml TEMPLATE_YAML]
                               [--ssh-server-port SSH_SERVER_PORT]
                               [--namespace NAMESPACE] [--max-pods MAX_PODS]
                               [--use-owner-token] [--standalone-mode]
                               [--child-report-tags CHILD_REPORT_TAGS [CHILD_REPORT_TAGS ...]]__

After manually creating the queue through ui, and disabling the variable from the values.yaml it does work.

### What's your helm version?

latest

### What's your kubectl version?

1.30

### What's the chart version?

latest

**Comment by filippo-clearml** [comment] 2024-08-20 13:31
Hey @cedricve - Closing this issue as a duplicate of #293

**Closed by filippo-clearml** 2024-08-20 13:31 UTC
Labels: bug
