### ISSUE TITLE
Clear ML Serving ingress doesn't work

### ISSUE THREAD

**Issue by Dundonis** [allegroai/clearml-helm-charts#225] opened 2023-06-13 10:54 UTC
Hi, it looks strange, but I can't access served model via ingress, as I understand interference model expose my model on path /serve/\<module\>. When I try to reach out via port forwarding of service inside my K8s Cluster it works, but when I am trying to do the same via ingress, I am getting 502 error. 

Helm: 
allegroai/clearml-serving --version 1.1.0
allegroai/clearml-agent --version 5.0.1 
allegroai/clearml --version 7.2.0

What value should be set in this var `defaultBaseServeUrl`  I have tried "http://127.0.0.1:8080/serve" "http://0.0.0.0:8080/serve" and "https://\<my-interferance-domain\>:8080/serve" ?

Screenshots:

![image](https://github.com/allegroai/clearml-serving/assets/63404719/5194dd2a-a35b-4003-a366-6b640d27aa35)
![image](https://github.com/allegroai/clearml-serving/assets/63404719/48e8f509-dc6f-48b8-a299-06a4bc1b6e50)

**Comment by valeriano-manassero** [comment] 2023-06-13 13:32
Hi @Dundonis ,
I'm going to try to reproduce issue on one of my testing clusters and will get back to you here asap

**Comment by Dundonis** [comment] 2023-06-13 16:00
@valeriano-manassero  command to install

```
helm upgrade clearml-serving allegroai/clearml-serving --version 1.1.0 `
--install `
--namespace clearml-serving `
--create-namespace `
-f .\clearml-serving-override.yaml
````

**Comment by valeriano-manassero** [comment] 2023-06-14 07:58
I tried your configuration but I didn't get any issue on it, a couple of remarks that may be useful:
* `defaultBaseServeUrl` doesn't;'t need to be overridden
* same url path must be used with ingress controller so `https://<my-interferance-domain>/serve/<id>`
* ingressClass `dev` must exists in k8s and be managed by your ingress controller
* if you get http code 502 it means the issue is on ingress controller itself, you can try to exec into one of controllers pod and try to curl internal svc to check if it's reachable from there, if not you need to check platform itself (internal dns, network policies and so on)

**Comment by Dundonis** [comment] 2023-06-14 08:17
Hmmm, it's weird, I was able to request with forwarding of service object, we have about 30 ingress objects, and they work fine. Okay, I'll dig deeper. Anyway thank you

**Comment by Dundonis** [comment] 2023-06-14 08:43
Additional Information. I am getting status code 499, it appears intermittently during the request and in the end I got 502. Should I add some ingress annotation?



`[14/Jun/2023:08:38:23 +0000] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" 530 25.025 [clearml-serving-clearml-serving-inference-8080] [] 10.244.3.112:8080 0 25.024 - baf9fabcabe4bf4e91c3532423e2d68`

`[14/Jun/2023:08:38:57 +0000] "GET /serve/emb_test_model HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" 668 392.727 [clearml-serving-clearml-serving-inference-8080] [] 10.244.3.112:8080, 10.244.3.112:8080, 10.244.3.112:8080 0, 0, 0 130.586, 131.070, 131.074 502, 502, 502 7601c505124f6084d309c0d245ef8a71`

**Comment by valeriano-manassero** [comment] 2023-06-14 09:14
this is pretty different; 499 is client dropping connection. Do you have any LB in front of your k8s cluster?

**Comment by valeriano-manassero** [comment] 2023-06-14 09:20
Moreover, I'm not totally sure in your case but these annotations for nginx ingress rule can help:
```
nginx.ingress.kubernetes.io/proxy-connect-timeout
nginx.ingress.kubernetes.io/proxy-send-timeout
nginx.ingress.kubernetes.io/proxy-read-timeout
nginx.ingress.kubernetes.io/proxy-next-upstream-timeout
```

**Comment by Dundonis** [comment] 2023-06-14 12:07
Yes, we have Azure LB Standard, I thought that the WAF might be blocking the connection, I also tried to disable it, but the same error. The annotations didn't help either.

**Comment by Dundonis** [comment] 2023-06-14 13:56
Hmm, I got 404 `curl` http://localhost/serve/emb_test_model -L`

**Comment by Dundonis** [comment] 2023-06-14 14:02
I also tried this `curl -X POST "http://localhost/serve/emb_test_model" -H "accept: application/json" -H "Content-Type: application/json" -d '{ "text": "Helle world!"}' -L` result the same

**Comment by valeriano-manassero** [comment] 2023-06-14 14:07
Since you are calling nginx directly from container, you need to pass headers with hostname otherwise it's not possible for it to serve right virtual host, add `-H "host: <hostname>"`

**Comment by Dundonis** [comment] 2023-06-14 14:34
Could you share your ingress configMap and version of ingress controller?

**Comment by valeriano-manassero** [comment] 2023-06-14 14:40
I'm using latest helm chart for ingress-nginx that uses controller 1.8.0. Configmap is basically empty since nginx.conf is used inside container to serve virtual hosts.

Debugging an ingress controller can be tricky, I suggest to ask for help on #ingress-nginx channel on the Kubernetes Slack server since issue doesn't look directly connected to clearml-serving chart.

**Comment by valeriano-manassero** [comment] 2023-06-15 14:21
I'm going to close this one since it doesn't seem related chart.

Feel free to reopen if there are any findings that will require fixing by me 😸

**Closed by valeriano-manassero** 2023-06-15 14:21 UTC
Labels: bug, good first issue

**Comment by Dundonis** [comment] 2023-06-19 13:40
Hi @valeriano-manassero I finally solved this problem, the problem is with network policy, when I removed it, it helped. But I have no idea why this policy is not working, everything looks good.

**Comment by Dundonis** [comment] 2023-06-19 13:47
I mean this policy, from Clearml-serving repo 
![image](https://github.com/allegroai/clearml-helm-charts/assets/63404719/755d8497-88a6-496b-837a-bfdb073ab35a)
